/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Looker Data Sciences, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

import React, { useEffect, useState, useContext, Component } from 'react'
import '../App.css'
import { ExtensionContext } from '@looker/extension-sdk-react'
import {
  Space,
  ComponentsProvider,
  Text,
  Box,
  Link,
  Flex,
  FlexItem,
  MenuList,
  MenuItem,
  MenuItemProps,
  Menu as MenuHeader
} from '@looker/components'
import { ROUTES } from '../Router'
import { Link as Linker, LinkProps } from 'react-router-dom'
import {
  Home as HomeIcon,
  Dashboard as DashboardsIcon,
  ModelTraining as ModelsIcon,
  ScatterPlot as RelValIcon,
  SwapHoriz as EtradeIcon,
  FilterAlt as ScreenerIcon,
  MenuBook as DataDictionaryIcon,
  Insights as InsightsIcon,
  Analytics as MarketDataIcon,
  TrendingUp as ForecastsIcon,
} from '@styled-icons/material'

const menuBackgroundColor = "#1f2436"

const buttonHighlightColor = "#2A2E39"

function traverseDescendants(node, highlightColor) {

  node.style.backgroundColor = highlightColor
  if (node.children.length > 0) {
    for (let i = 0; i < node.children.length; i++) {
      traverseDescendants(node.children[i], highlightColor)
    }
  }
}

function highlightBackground(e) {

  let targ = e.target.parentNode.parentNode.parentNode
  if (targ.className.substring(0, 4) === "Flex") {
    let linkerClassName = e.target.parentNode.parentNode.className
    switch (linkerClassName) {
      case "link0":
        targ = targ.children[0];
        break;
      case "link1":
        targ = targ.children[1];
        break;
      case "link3":
        targ = targ.children[3];
        break;
      case "link4":
        targ = targ.children[4];
        break;
      case "link5":
        targ = targ.children[5];
        break;
      case "link6":
        targ = targ.children[6];
        break;
      case "link7":
        targ = targ.children[7];
        break;
      case "link8":
        targ = targ.children[8];
        break;
      case "link9":
        targ = targ.children[9];
        break;
      default: // To combat possible bugs when the autogenerated className for the <Link> tag of Data Dictionary doesn't match Google Chrome's
        targ = targ.children[2];
        break;
    }
  }

  traverseDescendants(targ, buttonHighlightColor)
}

function unhighlightBackground(e) {

  let targ = e.target.parentNode.parentNode.parentNode
  if (targ.className.substring(0, 4) === "Flex") {
    let linkerClassName = e.target.parentNode.parentNode.className
    switch (linkerClassName) {
      case "link0":
        targ = targ.children[0];
        break;
      case "link1":
        targ = targ.children[1];
        break;
      case "link3":
        targ = targ.children[3];
        break;
      case "link4":
        targ = targ.children[4];
        break;
      case "link5":
        targ = targ.children[5];
        break;
      case "link6":
        targ = targ.children[6];
        break;
      case "link7":
        targ = targ.children[7];
        break;
      case "link8":
        targ = targ.children[8];
        break;
      case "link9":
        targ = targ.children[9];
        break;
      default: // To combat possible bugs when the autogenerated className for the <Link> tag of Data Dictionary doesn't match Google Chrome's
        targ = targ.children[2];
        break;
    }
  }

  traverseDescendants(targ, menuBackgroundColor)
}

class Menu extends React.Component {
  render() {
    return (
      <>
        <ComponentsProvider>
          <Box
            p="1px"
            display="flex"
            flexDirection="row"
            border-style="dotted solid"
            flex-basis="auto"
            width="100%"
            justifyContent="center"
            mx="auto"
            backgroundColor={menuBackgroundColor}
            height="50px"
          >
            <MenuList portal="false" children="false" type="none">
              <Flex flexDirection="row" >
                <Linker
                  className="link0"
                  to={ROUTES.HOMEPAGE_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<HomeIcon />} color="#9B9EA3" >
                    Homepage
                  </MenuItem>
                </Linker>

                <Linker
                  className="link1"
                  to={ROUTES.DASHBOARD_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<DashboardsIcon />} color="#9B9EA3" >
                    Dashboards
                  </MenuItem>
                </Linker>

                <Link
                  href="https://bondintelligence.cloud.looker.com/extensions/data_dictionary::data-dictionary/"
                  target="_blank"
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<DataDictionaryIcon />} color="#9B9EA3" >
                    Data Dictionary
                  </MenuItem>
                </Link>

                <Linker
                  className="link3"
                  to={ROUTES.MODELS_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  {/* <MenuHeader
                    content={
                      <>
                        <MenuItem icon={<ModelsIcon />} color="#9B9EA3">
                          Models
                        </MenuItem>
                        <MenuItem icon={<ModelsIcon />} color="#9B9EA3">
                          Models
                        </MenuItem>
                      </>
                    }
                  >
                    <MenuItem icon={<ModelsIcon />} color="#9B9EA3">
                      Models
                    </MenuItem>
                  </MenuHeader> */}
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<ModelsIcon />} color="#9B9EA3" >
                    Models
                  </MenuItem>
                </Linker>

                <Linker
                  className="link4"
                  to={ROUTES.SCREENER_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<ScreenerIcon />} color="#9B9EA3" >
                    Screener
                  </MenuItem>
                </Linker>

                <Linker
                  className="link5"
                  to={ROUTES.RELVAL_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >

                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<RelValIcon />} color="#9B9EA3" >
                    RelVal
                  </MenuItem>
                </Linker>

                <Linker
                  className="link6"
                  to={ROUTES.ETRADE_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<EtradeIcon />} color="#9B9EA3" >
                    Etrade
                  </MenuItem>
                </Linker>

                <Linker
                  className="link7"
                  to={ROUTES.INSIGHT_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<InsightsIcon />} color="#9B9EA3" >
                    Insights
                  </MenuItem>
                </Linker>

                <Linker
                  className="link8"
                  to={ROUTES.MARKETDATA_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<MarketDataIcon />} color="#9B9EA3" >
                    Market Data
                  </MenuItem>
                </Linker>

                <Linker
                  className="link9"
                  to={ROUTES.FORECAST_ROUTE}
                  style={{
                    backgroundColor: menuBackgroundColor,
                    textDecoration: 'none'
                  }}
                >
                  <MenuItem onMouseEnter={highlightBackground} onMouseLeave={unhighlightBackground} icon={<ForecastsIcon />} color="#9B9EA3" >
                    Forecasts
                  </MenuItem>
                </Linker>
              </Flex>
            </MenuList>
          </Box>
        </ComponentsProvider>
      </>
    )
  }
}

export default Menu